In [1]:
import numpy as np

# 1. Broadcasting

In [3]:
# a) Add a 1D array `[1, 2, 3]` to each row of a 2D array `[[10, 20, 30], [40, 50, 60]]`.
# Expected: [[11, 22, 33], [41, 52, 63]]

a1d = np.array([1,2,3])
a2d = np.array([[10,20,30],[40,50,60]])
a1d+a2d

array([[11, 22, 33],
       [41, 52, 63]])

In [18]:
# b) Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise.
# Expected: [[10, 20], [60, 80]]
a1d=np.array([10,20])
a2d = np.array([[1,2],[3,4]])
a1d = a1d.reshape(2,1)
a1d*a2d

array([[10, 20],
       [60, 80]])

# 2. Indexing and Slicing (High Dimensional Arrays)

In [19]:
arr = np.arange(1, 25).reshape(2, 3, 4)

In [25]:
# a) Extract the second slice along axis 0.
# Expected: [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
arr[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
# b) Extract all rows and the last column for all slices.
# Expected: [[4, 8, 12], [16, 20, 24]]
arr[:,:,-1]

array([[ 4,  8, 12],
       [16, 20, 24]])

In [27]:
# c) Reverse the order of slices along axis 0.
# Expected: [[[13, 14, 15, 16], ...], [[1, 2, 3, 4], ...]]
arr[::-1]

array([[[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [28]:
# d) Set all even elements in the array to -1.
# Expected: All even numbers replaced by -1.
arr[arr%2==0] = -1
arr

array([[[ 1, -1,  3, -1],
        [ 5, -1,  7, -1],
        [ 9, -1, 11, -1]],

       [[13, -1, 15, -1],
        [17, -1, 19, -1],
        [21, -1, 23, -1]]])

# 3. np.repeat

In [31]:
# a) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where every odd element is repeated twice.
# Expected: [1, 1, 3, 3, 5, 5]
arr = np.array([1,2,3,4,5,6])
np.repeat(arr[arr%2!=0], 2)

array([1, 1, 3, 3, 5, 5])

In [32]:
# b) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where elements are repeated based on their value.
# For example, `1` is repeated once, `2` twice, etc.
# Expected: [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, ...]
arr = np.array([1, 2, 3, 4, 5, 6])
np.repeat(arr,arr)

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6])

# 4. Normalizing

In [42]:
# a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.
# Expected: [0.0, 0.5, 1.0]
arr = np.array([10,20,30])
(arr-arr.min())/(arr.max()-arr.min())

array([0. , 0.5, 1. ])

# 5. Bonus Challenge

In [44]:
# a) Create a 3x3 matrix where each element at position (i, j) is i * j.
# Expected: [[0, 0, 0], [0, 1, 2], [0, 2, 4]]
arr = np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)
arr

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [49]:
# b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
# Expected: Diagonal elements replaced with 0.
arr = np.random.randint(1,10,(4,4))
np.fill_diagonal(arr,0)
print(arr)

[[0 2 8 4]
 [4 0 8 9]
 [4 1 0 6]
 [1 5 7 0]]
